config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  resources :outfits, except: [:edit, :update] do
    member do
      post 'add_item'
      post 'remove_item'
    end
  end

  resources :tags, only: [:show]
    # the next block doesn't need to be indented
    resources :items do
      require "carrierwave"
        # nice use of custom routes
        get "closet", on: :collection
        get "wishlist", on: :collection
        get "archive", on: :collection
        put "add_to_wishlist", on: :member
        put "add_to_closet", on: :member
        put "add_to_archive", on: :member
      resources :notes
      resources :taggings, only: [:new, :create, :destroy]
    end
end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates :description, presence:true, length: {in: 5..150}

  has_many :notes, dependent: :destroy
  has_many :taggings

  has_many :styles
  has_many :outfits, through: :styles
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :body, presence:true, length: {in: 3..250 }

  belongs_to :item
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  has_many :styles, dependent: :destroy
  has_many :items, through: :styles
end

app/models/style.rb
class Style < ActiveRecord::Base
  belongs_to :item
  belongs_to :outfit
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :items, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :item
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
def index
  @items = Item.where(archive: false)
end

def closet
  @items = Item.where(wishlist: false, archive: false)
  render :index
end

# nice use of custom actions paired with routes
def add_to_closet
  @item = Item.find(params[:id])
  @item.update(:wishlist => false, :archive => false)

  redirect_to items_path, notice: "Item added to closet"
end

def archive
  @items = Item.where(archive: true)
  render :archive
end

def add_to_archive
  @item = Item.find(params[:id])
  @item.update(archive: true)

  redirect_to items_path, notice: "Item added to archives"
end

def wishlist
  @items = Item.where(wishlist: true)
  render :index
end

def add_to_wishlist
  @item = Item.find(params[:id])
  @item.update(wishlist: true)

  redirect_to wishlist_items_path, notice: "Item added to wishlist"
end

def show
  @items = Item.where(archive: false)
  @item = Item.find(params[:id])
  @tagging = Tagging.new
end

def new
  @item = Item.new()
end

def create
  @item = Item.create(item_params)
  if @item.save
    redirect_to @item, notice: "New Item Created"
  else
    render 'new'
  end
end

def edit
  @items = Item.all
  @item = Item.find(params[:id])
end

def update

  @item = Item.find(params[:id])
  if @item.update(item_params)
    redirect_to @item, notice: "Item Successfully Changed"
  else
    @items = Item.where(archive: false)
    render 'edit'
  end
  # nice use of error handling paired with validations!
end

def destroy
  @item = Item.find(params[:id])
  @item.destroy
  redirect_to items_path, notice: "Item Discarded"
end

private
def item_params
  params.require(:item).permit(:description, :image, :value, :brand, :size, :fabric, :garment_care, :wishlist)
end #this is a clue that everything above should be indented one level
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
# inconsistent indentation across controllers
def create
  @item = Item.find(params[:item_id])
  @note = @item.notes.create(note_params)
  redirect_to item_path(@item)
end

def destroy
  @item = Item.find(params[:item_id])
  @note = @item.notes.find(params[:id])
  @note.destroy
  redirect_to item_path(@item)
end

private
  def note_params
    params.require(:note).permit(:author, :body)
  end

end

app/controllers/outfits_controller.rb
class OutfitsController  < ApplicationController
  def index
    @outfits = Outfit.all
    @outfit = Outfit.new
  end

  def show
    @outfit = Outfit.find(params[:id])
  end

  def create
    @outfit = Outfit.new(outfit_params)
    # this will work much better with validations for outfits in the outfit model, also this code doesn't need to be indented
      if @outfit.save
        redirect_to @outfit
      else
        render :new
      end
  end

  def destroy
    @outfit = Outfit.find(params[:id])
    @outfit.destroy
    redirect_to outfits_url
  end

  def add_item
    @outfit = Outfit.find(params[:id])
    @outfit.styles.create(item_id: params[:item_id])
    redirect_to @outfit
  end

  def remove_item
    @outfit = Outfit.find(params[:id])
    styles = @outfit.styles.where(item_id: params[:item_id]).destroy_all
    redirect_to @outfit
  end

  private
  def outfit_params
    params.require(:outfit).permit(:name)
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  def new
    @item = Item.find(params[:item_id])
    @tagging = @item.taggings.new
  end

  def create
    @item = Item.find(params[:item_id])
    @tag = Tag.find_or_create_by(name: params[:tag_name])

    existing_tagging = Tagging.find_by(item: @item, tag: @tag)
      unless existing_tagging
        @item.taggings.create(tag: @tag)
      end
      redirect_to item_path(@item)
  end

  def destroy
    @item = Item.find(params[:item_id])
    @tagging = @item.taggings.find(params[:id])
    @tagging.destroy
    redirect_to item_path(@item)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @items = @tag.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/tagging_helper.rb
module TaggingHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@item.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
         <% @item.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
    </div>
    <% end %>

  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :value %>
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </p>
  <p>
    <%= f.label :size %>
    <%= f.text_field :size %>
  </p>
  <p>
    <%= f.label :composition %>
    <%= f.text_field :composition %>
  </p>
  <p>
    <%= f.label :garment_care %>
    <%= f.text_field :garment_care %>
  </p>
  <p>
    <%= f.label :wishlist, "Add to: Closet" %>
    <%= f.radio_button :wishlist, false, :value => true %>
    <%= f.label :wishlist, "Wishlist" %>
    <%= f.radio_button :wishlist, true, :value => true %>
  <p>
    <%= f.submit%>
  </p>
  <% end %>

app/views/items/_item.html.erb
  <li class="specs description"><%= @item.description %></li>
  <% if @item.value %>
    <li class="specs">Estimated value: <%= number_to_currency(@item.value, :unit => "$") %></li>
  <% end %>

  <% if @item.brand && @item.brand.length > 0 %>
    <li class="specs">Brand: <%= @item.brand %></li>
  <% end %>

  <% if @item.size && @item.size.length > 0 %>
    <li class="specs">Size: <%= @item.size %></li>
  <% end %>

    <li class="specs">Composition: <%= @item.composition %></li>


  <% if @item.garment_care && @item.garment_care.length > 0 %>
    <li class="specs">Care: <%= @item.garment_care %></li>
  <% end %>

  <%= link_to 'Change', edit_item_path(@item) %>
  <%= link_to 'Discard', item_path(@item), method: :delete, data: {confirm: 'Are you sure?'}%>
  <%= link_to 'Archive', add_to_archive_item_path(@item), method: :put%>
    <% if !@item.wishlist %>
      <%= link_to '+ Wishlist', add_to_wishlist_item_path(@item), method: :put%>
    <% else %>
    <%= link_to '+ Closet', add_to_closet_item_path(@item), method: :put%>
  <% end %>

app/views/items/_items.html.erb
<% if @item %>
<%= image_tag(@item.image, class: "thisitem") %>
<% end %>
<% @items.each do |item| %>
  <% unless @item && item.id == @item.id %>
    <%= link_to image_tag(item.image), item_path(item) %>
    <% end %>
  <% end %>

app/views/items/archive.html.erb
<section class="new">
  <h2>Archives</h2>

  <div class="specs">
    <% @items.each do |item| %>
      <p>
        <%= item.description %>
        <%= link_to '(restore)', add_to_closet_item_path(item), method: :put %>
      </p>
        <% if item.notes.length > 0 %>
          <p>Notes: </p>
        <% end %>
            <% item.notes.each do |note| %>
              <li><%= note.body %></li>
            <% end %>
    <% end %>
  </div>
</section>

app/views/items/edit.html.erb
<section class="indexshow">
  <%= render 'items' %>
</section>

<section class="edit">
<div class="edit">
  <%= render 'form' %>
  <p><%= link_to 'Go back', item_path(@item) %></p>
</div>

</section>

app/views/items/index.html.erb
<section class="index">
  <%= render 'items' %>
</section>

app/views/items/new.html.erb
<h2 class="new">Add a new item</h2>
<section class="new">
  <%= render 'form' %>
</section>

app/views/items/show.html.erb
<section class="indexshow">

  <%= render 'items' %>

</section>

<section class="show">

  <div class="specs">
    <%= render 'item' %>
  </div>

  <%= render 'notes/notes' %>

  <%= render 'notes/form' %>

  <%= render 'taggings/show' %>

  <%= render 'taggings/form' %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>aeterna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet' type='text/css'>
</head>
<body>
<a href="/">
<header>
  A<span>ETERNA</span>
</header></a>
<nav>
<li class="nav link"><%= link_to 'closet', closet_items_path %></li>
<li class="nav link"><%= link_to 'wishlist', wishlist_items_path %></li>
<li class="nav link"><%= link_to 'archives', archive_items_path %></li>
<li class="nav link"><%= link_to 'new item', new_item_path %></li>
<li class="nav link"><%= link_to 'outfits', outfits_path %></li>
</nav>
<% flash.each do |type, message| %>
<p class="<%= type %>"><%= message %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for([@item, @item.notes.build]) do |f| %>
<%= f.text_field :body, placeholder: 'NEW NOTE'%>
<%= f.submit "+ NOTE"%>
<% end %>

app/views/notes/_note.html.erb
<div class="note">
  <span class="delete_note">
    <%= link_to 'X', [note.item, note],
    method: :delete,
    data: {confirm: 'Delete this note? (This action cannot be undone.)'}%>
  </span>

  <span class="body_note">
    <%= note.body %>
  </span>

  <span class="update_note">
    Updated <%= time_ago_in_words(note.created_at) %>
  </span>

</div>

app/views/notes/_notes.html.erb
<div class="notes">
  <% if @item.notes.length > 0 %>
    <p>Notes</p>
    <li class="notes"><%= render @item.notes %></li>
  <% end %>

app/views/outfits/_new.html.erb
<h2>New Outfit</h2>

<%= form_for(@outfit) do |f| %>

  <%= f.text_field :name, placeholder: 'NAME'%>

  <%= f.submit %>

<% end %>

app/views/outfits/index.html.erb
<section class="new">
  <%= render 'new' %>
</section>

<section class="show">
  <div class="specs">
    <h2>Outfits</h2>
    <% @outfits.each do |outfit| %>
      <p>
        <%= link_to outfit.name, outfit %>
        <%= link_to 'x', outfit_path(outfit), method: :delete %>
      </p>
    <% end %>
  </div>
</section>

app/views/outfits/show.html.erb
<section class="new">
  <h2><%= @outfit.name %></h2>
  <section class="index">

    <% @outfit.items.each do |item| %>
        <div>
          <%= link_to image_tag(item.image), item_path(item) %>
          <%= link_to "x", remove_item_outfit_path(@outfit, item_id: item.id), method: :post %>
        </div>
      <% end %>

  </section>

  <fieldset>
    <%= form_tag(add_item_outfit_path(@outfit)) do %>
      <%= select_tag(:item_id, options_for_select(Item.all.map{|i| ["#{i.description}", i.id]})) %>
      <%= submit_tag "Add Item" %>
    <% end %>
  </fieldset>
</section>

app/views/taggings/_form.html.erb
<%= form_for [@item, @tagging] do |f| %>
  <%= text_field_tag :tag_name %>
  <%= f.submit "+ TAG" %>
<% end %>

app/views/taggings/_show.html.erb
  <% if @item.taggings.length >0 %>
    Tags
  <% end %>
  <% @item.taggings.each do |tagging| %>
    <span class="tag">
      <%= link_to tagging.tag.name.downcase, tag_path(tagging.tag), :class =>"showtag" %><%= link_to 'x', [tagging.item, tagging],
      method: :delete, :title => "Delete Tag", :class => "deletetag"%>
  <% end %>

app/views/tags/show.html.erb
<h1>Tag: <%= @tag.name.upcase %></h1>
<section class="index">
  <%= render partial: 'items/items' %>
</section>